auctions/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create", views.create, name="create"),
    path("categories", views.categories, name="categories"),
    path("my_listings", views.my_listings, name="my_listings"),
    path("my_purchases", views.my_purchases, name="my_purchases"),
    path("active_biddings", views.active_biddings, name="active_biddings"),
    path("show_listing_categories", views.show_listing_categories, name="show_listing_categories"),
    path("watchlist", views.show_watchlist, name="watchlist"),
    path("<int:listing_id>/<str:listing_name>", views.show_listing, name="show_listing"),
    path("add_to_watchlist/<int:listing_id>", views.add_to_watchlist, name="add_to_watchlist"),
    path("remove_from_watchlist/<int:listing_id>", views.remove_from_watchlist, name="remove_from_watchlist"),
    path("add_comment/<int:listing_id>", views.add_comment, name="add_comment"),
    path("place_a_bid/<int:listing_id>", views.place_a_bid, name="place_a_bid"),
    path("close_listing/<int:listing_id>", views.close_listing, name="close_listing")

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


def user_directory_path(instance, filename):
    # File will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return "user_{0}/{1}".format(instance.seller.id, filename)

class User(AbstractUser):
    pass

class Listing(models.Model):
    name = models.CharField(max_length=64)
    date = models.DateTimeField(blank = True)
    price = models.DecimalField(max_digits=12, decimal_places=2)
    description = models.CharField(max_length=1000)
    NEW = 'N'
    LIKE_NEW = 'LN'
    USED_GOOD = 'UG'
    USED_FAIR = 'UF'
    USED_POOR = 'UP'
    DAMAGED = 'DMG'
    CONDITION_CHOICES = {
        (NEW, 'New'),
        (LIKE_NEW, 'Like New'),
        (USED_GOOD, 'Used - Good'),
        (USED_FAIR, 'Used - Fair'),
        (USED_POOR, 'Used - Poor'),
        (DAMAGED, 'Damaged',)
    }
    condition = models.CharField(
        max_length=3,
        choices=CONDITION_CHOICES,
    )
    GARDEN_AND_DIY = 'G&DIY'
    CHILD = 'CHLD'
    ELECTRONICS = "ELECT"
    ARTS = 'ARTS'
    ENTERTAINMENT = 'ENTER'
    FASHION = 'FSHN'
    MOTORIZATION = 'AUTO'
    REAL_ESTATES = 'REST'
    BEAUTY = 'BTY'
    CATEGORIES_CHOICES = {
        (GARDEN_AND_DIY, 'Garden & DYI'),
        (CHILD, 'Child'),
        (ELECTRONICS, 'Electronics'),
        (ARTS, 'Arts'),
        (ENTERTAINMENT, 'Entertainment'),
        (FASHION, 'Fashion'),
        (MOTORIZATION, 'Motorization'),
        (REAL_ESTATES, 'Real Estates'),
        (BEAUTY, 'Beauty'),
    }
    category = models.CharField(
        max_length=5,
        choices=CATEGORIES_CHOICES,
    )
    image = models.ImageField(upload_to=user_directory_path)
    image_thumbnail = ImageSpecField(source='image',
                                      processors=[ResizeToFill(200, 200)],
                                      format='JPEG',
                                      options={'quality': 60})
    image_medium = ImageSpecField(source='image',
                                      processors=[ResizeToFill(350, 350)],
                                      format='JPEG',
                                      options={'quality': 60})
    image_large = ImageSpecField(source='image',
                                      processors=[ResizeToFill(500, 500)],
                                      format='JPEG',
                                      options={'quality': 60})
    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name = 'listings')
    active = models.BooleanField(default = True)
    sold_to = models.ForeignKey(User, on_delete=models.CASCADE, related_name = 'won_listing', null=True, blank=True)
    sold_for = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return self.name

class Bid(models.Model):
    bid = models.DecimalField(max_digits=12, decimal_places=2)
    bidder = models.ForeignKey(User, on_delete=models.CASCADE, related_name='bids')
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name='bids')

    def __str__(self):
        return (f"{self.listing} price is {self.bid}. Bidder is {self.bidder}.")

class Comment(models.Model):
    comment = models.CharField(max_length=1000, blank=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comments')
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="listing_comments")
    date = models.DateTimeField(blank = True)

    def __str__(self):
        return (f"{self.user} wrote {self.comment} under {self.listing} on {self.date}.")

class Watchlist(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="user_watchlist")
    listing = models.ManyToManyField(Listing, related_name="listings_on_watchlist")

    def __str__(self):
        return (f"{self.user}'s watchlist")
    

auctions/forms.py
from django import forms
from .models import Listing, Comment

# Create listing form
class ListingForm(forms.ModelForm):
    class Meta:
        # Access Listing model and take fields which will be included in the form
        model = Listing
        fields = [
            'name', 
            'price', 
            'description',
            'image',
            'condition',
            'category',
            ]
        widgets = {
            'name': forms.TextInput(attrs={'id': 'name_form'}),
            'price': forms.TextInput(attrs={'id': 'price_form'}),
            'description': forms.Textarea(attrs={'id': 'description_form', }),
            'image': forms.FileInput(attrs={'id': 'image_form'}),
            'condition': forms.Select(attrs={'id': 'condition_form'}),
            'category': forms.Select(attrs={'id': 'category_form'})
        }

# Create a comment form
class CommentForm(forms.ModelForm):
    class Meta:
        # Access comment model and take fields which will be included in the form
        model = Comment
        fields = [
            'comment'
        ]
        widgets = {
            'comment': forms.Textarea(attrs={'id': 'comment_form'}),
        }

# Choose a category form:
class CategoriesForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = [
            'category'
        ]

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import ListingForm, CommentForm
from django.contrib.auth.decorators import login_required
from .models import Listing, Watchlist, Comment, Bid
from .models import User
from datetime import datetime
import json
from django.core.paginator import Paginator


# Shows index page with all listings
def index(request):
    listings = Listing.objects.all().order_by("-date")
    if not listings:
        return render(request, "auctions/error.html")
    
    # Create paginator
    paginator = Paginator(listings, 10)
    # Get page number
    page_number = request.GET.get("page")
    # Create page object
    page_obj = paginator.get_page(page_number)

    return render(request, "auctions/index.html", {
        "page_obj": page_obj,
        "navbar": True
    })

# Login-in a user
def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html", {
            "navbar": True
        })


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match.",
                "navbar": True
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken.",
                "navbar": True
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html", {
            "navbar": True
        })


# Show and process a create listing form
@login_required(login_url='login')
def create(request):
    # Show a create listing form
    if request.method == "GET":
        # Get an empty create listing form
        form = ListingForm()
        if not form:
            error = "Can't retrieve a create listing form"
            return render(request, "auctions/error.html", {
                "error": error,
                "navbar": True
            })
        else:
            return render(request, "auctions/create.html", {
                "form": form,
                "navbar": True
            })
    else:
        # Get form filled with data provided by a user
        form = ListingForm(request.POST, request.FILES)
        if form.is_valid():
            # Get data from form
            name = form.cleaned_data["name"]
            price = form.cleaned_data["price"] 
            description = form.cleaned_data["description"]
            image = form.cleaned_data["image"]
            condition = form.cleaned_data["condition"]
            category = form.cleaned_data["category"]
            date = datetime.now()
            seller = request.user
            listing = Listing(
                name=name, 
                price=price,
                date=date, 
                description=description,
                image=image,
                condition=condition,
                category=category,
                seller = seller 
                )
            # Save data in database
            listing.save()
            return HttpResponseRedirect(reverse("index"))
        else:
            error = "Submitted form is invalid"
            return render(request, "auctions/error.html", {
                "error": error,
                "navbar": True
            })


@login_required(login_url='login')
def show_listing(request, listing_id, listing_name):
    if request.method == "GET":
        # Get all data about a single listing
        listing = Listing.objects.get(id=listing_id)
        if not listing:
            error = "Can't retrieve listings"
            return render(request, "auctions/error.html", {
                "error": error,
                "navbar": True
            })
        else:
            # Get empty comment form
            comment_form = CommentForm()

            # Get all comments related to a listing
            comments = Comment.objects.filter(listing=listing_id)

            # Get watchlist of a user (used to conditionally choose elements to be shown)
            try:
                watchlist = Watchlist.objects.get(user = request.user)
            except Watchlist.DoesNotExist:
                watchlist = None

            # Get 5 latest bids of a listing (used to conditionally choose elements to be shown)
            bids = Bid.objects.filter(listing=listing).order_by("-bid")[:5]
            if not bids:
                bids = None
                highest_bid = None
                highest_bid_plus_1 = None
            else:
                # Get highest bid QuerySet
                highest_bid_object = Bid.objects.filter(listing=listing).order_by("-bid").first()

                # Retrieve the heighest bid
                highest_bid = highest_bid_object.bid

                # Format highest bid to 2 decimal places
                highest_bid = round(float(highest_bid), 2)
                highest_bid_plus_1 = highest_bid + 0.01
                highest_bid = round(float(highest_bid), 2)

        return render(request, "auctions/listing.html", {
            "listing": listing,
            "watchlist": watchlist,
            "comment_form": comment_form,
            "comments": comments,
            "bids": bids,
            "highest_bid": highest_bid,
            "highest_bid_plus_1": highest_bid_plus_1,
            "navbar": True
        })


def categories(request):
    if request.method == "GET":
        # Look into each tuple of categories (ENTER, Entertainment)
        # and get 2nd value(Entertainment)
        # Pass it to a value and html
        all_categories = [c for c in Listing.CATEGORIES_CHOICES]
        return render(request, "auctions/categories.html", {
            "all_categories": all_categories,
            "navbar": True
        })
    
def show_listing_categories(request):

    # Get user chosen category
    category = request.GET.get('data')
    if category is None:
        error = "Can't retrieve selected category"
        return render(request, "auctions/error.html", {
            "error": error,
            "navbar": True
        })
    else:
        listings = Listing.objects.filter(active=True).filter(category=category).order_by("-date")
        if not listings:
            listings = None
            return JsonResponse({"listings": listings})
        else:
            # Get condition of each listing
            all_conditions = [c for c in Listing.CONDITION_CHOICES] 
            
            final_list = []
            # Convert each instance in the QuerySet into a dictionary
            for key in listings.values():
                for condition in all_conditions:
                    # Amend condition within final list
                    # Good practice of making copies
                    if key["condition"] == condition[0]:
                        # Then convert the entire QuerySet into a list of those dictionaries.
                        final_list.append(key)
                        key["condition"] = condition[1]
            
            return JsonResponse({"listings": final_list})

@login_required(login_url='login')
def my_listings(request):
    if request.method == "GET":
        # Get user
        user = request.user
        user_listings = Listing.objects.filter(seller=user).order_by("-date")
        if not user_listings:
            user_listings = None
            return render(request, "auctions/my_listings.html", {
                "user_listings": user_listings,
                "navbar": True
            })
        else:
            # Create paginator
            paginator = Paginator(user_listings, 4)
            # Get page number
            page_number = request.GET.get("page")
            # Create page object
            user_listings = paginator.get_page(page_number)
            return render(request, "auctions/my_listings.html", {
                "user_listings": user_listings,
                "navbar": True
            })

@login_required(login_url='login')
def my_purchases(request):
    if request.method == "GET":
        # Get user
        user = request.user
        user_purchases = Listing.objects.filter(sold_to=user).order_by("-date")
        if not user_purchases:
            user_purchases = None
            return render(request, "auctions/my_purchases.html", {
                "user_purchases": user_purchases,
                "navbar": True
            })
        else:
            # Create paginator
            paginator = Paginator(user_purchases, 4)
            # Get page number
            page_number = request.GET.get("page")
            # Create page object
            user_purchases = paginator.get_page(page_number)

auctions/templates/auctions/active_biddings.html
{% extends "auctions/layout.html" %}

{% block body %}
{% if active_biddings %}
    <h2>You bid on following listings</h2>
        <div class="all_listings">
            {% for listing in active_biddings %}
                <div class="listing">
                    <a href="{% url 'show_listing' listing.id listing.name %}">
                        <div class="image_box">
                            <img src="{{ listing.image.url }}" 
                                    srcset="{{ listing.image_thumbnail.url }} 200w, 
                                            {{ listing.image_medium.url }} 350w,
                                            {{ listing.image_large.url }} 500w"
                                    sizes="(max-width: 480px) 90vw, (max-width: 800px) 50vw"
                                    alt="{{ listing.description }}" 
                                    class="justify-content-center" />
                        </div>
                        <div class="nameprice_box">
                            <p class="listing-name">{{ listing.name }}</p>
                            <p class="listing-price">PLN {{ listing.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>

        <!-- Pagination -->
        <div class="pagination">
            <span class="step-links">
                {% if active_biddings.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ active_biddings.previous_page_number }}">previous</a>
                {% endif %}
        
                <span class="current">
                    Page {{ active_biddings.number }} of {{ active_biddings.paginator.num_pages }}.
                </span>
        
                {% if active_biddings.has_next %}
                    <a href="?page={{ active_biddings.next_page_number }}">next</a>
                    <a href="?page={{ active_biddings.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
{% else %}
<h2> You don't bid on anything</h2>
{% endif %}
{% endblock %}

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Categories</h2>

    <form action ="{% url 'categories' %}" method="get" name="categories" id="categories_form">
        <select class="my_buttons" id="selected_category">
            <option class="my_buttons" selected="true" disabled="disabled">Category</option>  
            {% for category in all_categories %}
            <option class="my_buttons" value="{{ category.0 }}">{{ category.1 }}</option>
            {% endfor %}
        </select>
    </form>
    <hr>

    <div class="all_listings">
        <!-- Populated depending on user's choice from select form-->
    </div>
{% endblock %}

auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}

{% block body %}
<h2>Create a new listing</h2>

<form action="{% url 'create' %}" method="post" enctype="multipart/form-data" id="create_form">
    {% csrf_token %}
    {{ form }}
    <div>
        <input type="submit" value="Submit" class="my_buttons">
    </div>
</form>

{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>
    <div class="all_listings">
        {% for listing in page_obj %}
        {% if listing.active == True %}
        <div class="listing">
            <a href="{% url 'show_listing' listing.id listing.name %}">
                <div class="image_box">
                    <img src="{{ listing.image.url }}" 
                        srcset="{{ listing.image_thumbnail.url }} 200w, 
                                {{ listing.image_medium.url }} 350w,
                                {{ listing.image_large.url }} 500w"
                        sizes="(max-width: 480px) 90vw, (max-width: 800px) 50vw"
                        alt="{{ listing.description }}" 
                        class="justify-content-center" />
                </div>
                <div class="nameprice_box">
                    <p class="listing_name">{{ listing.name }}</p>
                    <p class="listing_price">PLN {{ listing.price }}</p>
                </div>
            </a>
        </div>

                        <!-- <p id="listing-category">{{ listing.get_category_display }}</p> -->
        {% endif %}
        {% endfor %}
        </div>

        <!-- Pagination -->
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
        
                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
        
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
{% endblock %}

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block body %}

<div class="wrapper">
    <!-- Listing -->
    <div class="listing_name">
        <h1 class="listing_name_big">{{ listing.name }}</h1>
    </div>
    <div class="image">
        <img src="{{ listing.image.url }}" 
                srcset="{{ listing.image_thumbnail.url }} 200w, 
                        {{ listing.image_medium.url }} 350w,
                        {{ listing.image_large.url }} 500w"
                sizes="(max-width: 480px) 100vw, (max-width: 800px) 50vw"
                alt="{{ listing.description }}" 
                class="justify-content-center listing_image" />
    </div>
    <div class="main_info">
        <p class="listing_seller_big"><strong>Posted by:</strong> {{ listing.seller }}</p>
        <p class="listing_description"><strong>Description:</strong> {{ listing.description }}</p>
        {% if not bids %}
        <!-- Actual live  -->
        <p class="listing_price_big"><strong>Price:</strong> PLN {{ listing.price }}</p>
        {% else %}
        <p class="listing_price_big"><strong>Price:</strong> PLN {{ highest_bid }}</p>
        {% endif %}
        <p class="listing_condition"><strong>Condition: </strong> {{ listing.get_condition_display }}</p>
        <p class="listing_date"><strong>Added:</strong> {{ listing.date }}</p>
    </div>
    
    <!-- History of bids -->
    <div class="bids">
        {% if not bids %}
        <h4 id="no_bids">No bids on this listing!</h4>
        {% else %}
        <div id="tabelka">
            <table>
                <caption>
                    <h4 id="table_caption">Highest bids</h4>
                </caption>
                <thead>
                    <tr>
                        <th scope="col">Price</th>
                        <th scope="col">User</th>
                    </tr>
                </thead>
                <tbody>
                    
                    {% for bid in bids %}
                    <tr>
                        <td>{{bid.bid}}</td>
                        <td>{{bid.bidder}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
    
    
    
        <!-- Form and button for placing a bid -->
        {% if listing.active == False or user == listing.seller %}
        <div id="empty"></div>
        <!-- <form inert action ="{% url 'place_a_bid' listing.id %}" method="post", name="place_a_bid_form" id="place_a_bid_form"> -->
            {% else %}
            <div>
                <form action="{% url 'place_a_bid' listing.id %}" method="post" , name="place_a_bid_form" id="place_a_bid_form">
                    {% csrf_token %}
                    <input type="hidden" value="{{ listing.id }}" name="listing_id">
                    {% if bids %}
                    <input type="number" placeholder="{{ highest_bid_plus_1 }}" id="bid" min="{{ highest_bid_plus_1 }}"
                    max="999999999999" step="0.01" required>
                    <input type="submit" class="my_buttons" value="Place a bid">
                    {% else %}
                    <input type="number" placeholder="{{ listing.price }}" id="bid" min="{{ listing.price }}" max="999999999999"
                    step="0.01" required>
                    <input type="submit" class="my_buttons" value="Place a bid">
                    {% endif %}
                </form>
            </div>
            {% endif %}
    </div>
    
    <div class="all_forms">  
        <!-- Form to close a listing -->
        {% if listing.sold_to is None and user == listing.seller %}
        <h3 id="sold_to_banner">Listing not sold</h3>
        {% elif not listing.active %}
        <h3 id="sold_to_banner">Sold to user {{ listing.sold_to }}</h3>
        {% endif %}
        
        <div>
            {% if listing.active and user == listing.seller %}
            <div class="button_container">
                <div class="button_and_form">
                    <form action="{% url 'close_listing' listing.id %}" method="post" name="close_listing">
                        {% csrf_token %}
                        <input type="hidden" value="{{ listing.id }}" name="listing_id">
                        <input type="submit" value="Close Listing" class="my_buttons">
                    </form>
                </div>
            </div>
        </div>
        {% endif %}        
    </div>

    <!-- Add to watchlist form -->
    {% if listing.active and user != listing.seller %}
    <form action="{% url 'add_to_watchlist' listing.id %}" method="post" name="add_to_watchlist_form" id="add_to_watchlist_form">
        {% csrf_token %}
        <input type="hidden" value="{{ listing.id }}" name="listing_id">
        {% if listing in watchlist.listing.all %}
        <input type="submit" value="Remove from watchlist" class="my_buttons" id="add_to_watchlist">
        {% else %}
        <input type="submit" value="Add to watchlist" class="my_buttons" id="add_to_watchlist">
        {% endif %}
    </form>
    {% endif %}
</div>
</div>

<!-- Comment sections -->
<div id="comment_section">
    <h4 id="comment_heading">Comments</h4>
    {% if listing.active == False %}
    <form action="{% url 'add_comment' listing.id %'}" method="post" class="comment_form" name="add_comment_form"
    id="add_comment_form">
    </form>
    {% else %}
    <form action="{% url 'add_comment' listing.id %'}" method="post" class="comment_form" name="add_comment_form"
    id="add_comment_form">
        {% csrf_token %}
        <input type="hidden" value="{{ listing.id }}" name="listing_id">
        {{ comment_form }}
        <input type="submit" value="Add Comment" class="my_buttons" id="add_comment">
    </form>
    {% endif %}

    <div>
        <p id="empty_comment">The comment cannot be empty</p>
    </div>

    <!-- All comments -->
    <div id="all_comments_wrapper">
        {% for comment in comments %}
        <div class="one_comment_wrapper">
            <p class="comment">
                {{ comment.comment }}
            </p>
            <p class="commenter">
                {{ comment.user }}
            </p>
            <p class="comment_date">
                {{ comment.date }}
            </p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}

{% if watchlist %}
    <h2 id="title">Your Watchlist</h2>
    <div class="all_listings">
        {% for listing in watchlist %}
            <div class="listing" id="listing_{{ listing.id }}">
                <a href="{% url 'show_listing' listing.id listing.name %}">
                    <div class="image_box">
                        <img src="{{ listing.image.url }}" 
                        srcset="{{ listing.image_thumbnail.url }} 200w, 
                                {{ listing.image_medium.url }} 350w,
                                {{ listing.image_large.url }} 500w"
                        sizes="(max-width: 480px) 90vw, (max-width: 800px) 50vw"
                        alt="{{ listing.description }}" 
                        class="justify-content-center" />
                    </div>
                    <div class="nameprice_box">
                        <p class="listing-name">{{ listing.name }}</p>
                        <p class="listing-price">PLN {{ listing.price }}</p>
                        <form action="{% url 'remove_from_watchlist' listing.id %}" method="post"
                            class="remove_from_watchlist" name="remove_from_watchlist">
                            {% csrf_token %}
                            <input type="hidden" value="{{ listing.id }}" name="listing_id" class="listing_id">
                            <input type="submit" value="Remove from watchlist" class="my_buttons">
                        </form>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>

    <!-- Pagination -->
    <div class="pagination">
        <span class="step-links">
            {% if watchlist.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ watchlist.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ watchlist.number }} of {{ watchlist.paginator.num_pages }}.
            </span>
    
            {% if watchlist.has_next %}
                <a href="?page={{ watchlist.next_page_number }}">next</a>
                <a href="?page={{ watchlist.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% else %}
    <h2 id="title">Your Watchlist is empty</h2>
{% endif %}
{% endblock %}
<!-- Display information about the listing -->

<!--  

            <div class="col-6 left_side image">
                <img src="{{ listing.image.url }}" alt="{{ listing.description }}" class="justify-content-center">
            </div>
            <div class="col-6 right_side">
                <div class="elo">
                    <h4 class="listing-name">{{ listing.name }}</h4>
                    <h4 class="listing-price">PLN {{ listing.price }}</h4>
                </div>
                <div class="lol"> -->
<!-- <p id="listing-category">{{ listing.get_category_display }}</p> -->
<!--    <p class="listing-condition">{{ listing.get_condition_display }}</p>
                    <p class="listing-date">{{ listing.date }}</p>
                </div>
            </div>
        </a>
    </div> -->
<!-- Remove from watchlist form -->